[tool.poetry]
name = "pc2mqtt"
version = "0.1.1"
description = ""
authors = ["Maxim Mityutko"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
paho-mqtt = "2.1.0"
pycaw = { version = "20240210", markers = "sys_platform == 'win32'" }

[tool.poetry.dev-dependencies]
pyinstaller = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
